const columns = [
  {
    field: 'managerName',
    headerName: '담당자',
    flex: 1,
    headerAlign: 'center',
    align: 'center',
    headerClassName: 'revenu-header-css',
  },
  {
    field: 'ownerName',
    headerName: '임대인',
    flex: 1,
    headerAlign: 'center',
    align: 'center',
    headerClassName: 'revenu-header-css',
  },
  {
    field: 'clientName',
    headerName: '임차인',
    flex: 1,
    headerAlign: 'center',
    align: 'center',
    headerClassName: 'revenu-header-css',
  },
  {
    field: 'propertyAddress',
    headerName: '주소',
    headerAlign: 'center',
    flex: 5,
    headerClassName: 'revenu-header-css',
  },
  {
    field: 'contractStartDate',
    headerName: '계약 시작일',
    flex: 1,
    headerAlign: 'center',
    align: 'center',
    headerClassName: 'revenu-header-css',
  },
  {
    field: 'contractEndDate',
    headerName: '계약 종료일',
    flex: 1,
    headerAlign: 'center',
    align: 'center',
    headerClassName: 'revenu-header-css',
  },
  {
    field: 'price',
    headerName: '가격',
    flex: 1,
    headerAlign: 'cashValue',
    align: 'center',
    headerClassName: 'revenu-header-css',
  },
  {
    field: 'commision',
    headerName: '수수료',
    flex: 1,
    headerAlign: 'center',
    align: 'center',
    headerClassName: 'revenu-header-css',
  },
  {
    field: 'remark',
    headerName: '특이사항',
    type: 'number',
    flex: 2,
    headerAlign: 'center',
    align: 'center',
    headerClassName: 'revenu-header-css',
  },
]

export default columns
